### ISSUE TITLE
Test - 分享推荐

### ISSUE THREAD

**Issue by itwangxiang** [itwangxiang/docs.bookey#5]
#  测试用例

### 推荐人 - 分享推荐给好友

1. 活动有效期内分享
   1. 推荐人数未满 10 人
   1. 推荐人数满 10 人
1. 活动有效期外分享
 
### 被推荐人 - 点击分享链接后

1. 首次注册登陆
1. 非首次注册登陆

### 非订阅

- [x] 推荐人 `1-i` 、被推荐人 `1`  => （+ 20 天 / + 10 天）
- [x] 推荐人 `1-i` 、被推荐人 `2`  => （+ 0 天 / + 0 天）
- [ ] 推荐人 `1-ii` 、被推荐人 `1`  => （+ 0 天 / + 10 天）
- [x] 推荐人 `1-ii` 、被推荐人 `2`  => （+ 0 天 / + 0 天）
- [ ] 推荐人 `2` 、被推荐人 `1`  => （+ 0 天 / + 10 天）
- [x] 推荐人 `2` 、被推荐人 `2`  => （+ 0 天 / + 0 天）

### 订阅

- [ ] 推荐人 `1-i` 、被推荐人 `1`  => （+ 20 天 / + 10 天）
- [ ] 推荐人 `1-i` 、被推荐人 `2`  => （+ 0 天 / + 0 天）
- [ ] 推荐人 `1-ii` 、被推荐人 `1`  => （+ 0 天 / + 10 天）
- [ ] 推荐人 `1-ii` 、被推荐人 `2`  => （+ 0 天 / + 0 天）
- [ ] 推荐人 `2` 、被推荐人 `1`  => （+ 0 天 / + 10 天）
- [ ] 推荐人 `2` 、被推荐人 `2`  => （+ 0 天 / + 0 天）

-- share@oo.oo - 2020/05/09

**Comment by itwangxiang** [comment]
## IOS 
推荐人 https://ohjcz.test-app.link/52AG1FYu65

**Comment by pengxiaoyan** [comment]
https://ohjcz.test-app.link/F5ksGrlw65

**Comment by pengxiaoyan** [comment]
https://ohjcz.test-app.link/MDITACjsj6

**Comment by pengxiaoyan** [comment]
https://ohjcz.test-app.link/yBB1BMmHj6

**Comment by pengxiaoyan** [comment]
https://ohjcz.test-app.link/EEbqxejIj6

**Comment by pengxiaoyan** [comment]
https://ohjcz.test-app.link/IVcJanOIj6

**Comment by pengxiaoyan** [comment]
https://ohjcz.test-app.link/5heB0G9Jj6

**Comment by pengxiaoyan** [comment]
https://ohjcz.test-app.link/KNTIC8hRk6

**Comment by pengxiaoyan** [comment]
https://ohjcz.test-app.link/wiuOgscSk6

**Comment by pengxiaoyan** [comment]
https://ohjcz.test-app.link/Cxl8GVOSk6

**Comment by pengxiaoyan** [comment]
https://ohjcz.test-app.link/A1JK7tcVk6

**Comment by pengxiaoyan** [comment]
https://ohjcz.test-app.link/ZGoCzc4Vk6

**Comment by pengxiaoyan** [comment]
https://ohjcz.test-app.link/3FLn0NHWk6

**Comment by itwangxiang** [comment]
## 测试结果 - Stephen

### 非订阅

- [ ] 推荐人 `1-i` 、被推荐人 `1`  => （+ 20 天 / + 10 天）
- [ ] 推荐人 `1-i` 、被推荐人 `2`  => （+ 0 天 / + 0 天）
- [ ] 推荐人 `1-ii` 、被推荐人 `1`  => （+ 0 天 / + 10 天）
- [ ] 推荐人 `1-ii` 、被推荐人 `2`  => （+ 0 天 / + 0 天）
- [ ] 推荐人 `2` 、被推荐人 `1`  => （+ 0 天 / + 10 天）
- [ ] 推荐人 `2` 、被推荐人 `2`  => （+ 0 天 / + 0 天）

### 订阅

- [ ] 推荐人 `1-i` 、被推荐人 `1`  => （+ 20 天 / + 10 天）
- [ ] 推荐人 `1-i` 、被推荐人 `2`  => （+ 0 天 / + 0 天）
- [ ] 推荐人 `1-ii` 、被推荐人 `1`  => （+ 0 天 / + 10 天）
- [ ] 推荐人 `1-ii` 、被推荐人 `2`  => （+ 0 天 / + 0 天）
- [ ] 推荐人 `2` 、被推荐人 `1`  => （+ 0 天 / + 10 天）
- [ ] 推荐人 `2` 、被推荐人 `2`  => （+ 0 天 / + 0 天）

**Comment by pengxiaoyan** [comment]
## 测试结果 - pxy

### 非订阅

- [ ] 推荐人 `1-i` 、被推荐人 `1`  => （+ 20 天 / + 10 天）
- [ ] 推荐人 `1-i` 、被推荐人 `2`  => （+ 0 天 / + 0 天）
- [ ] 推荐人 `1-ii` 、被推荐人 `1`  => （+ 0 天 / + 10 天）
- [ ] 推荐人 `1-ii` 、被推荐人 `2`  => （+ 0 天 / + 0 天）
- [ ] 推荐人 `2` 、被推荐人 `1`  => （+ 0 天 / + 10 天）
- [ ] 推荐人 `2` 、被推荐人 `2`  => （+ 0 天 / + 0 天）

### 订阅

- [ ] 推荐人 `1-i` 、被推荐人 `1`  => （+ 20 天 / + 10 天）
- [ ] 推荐人 `1-i` 、被推荐人 `2`  => （+ 0 天 / + 0 天）
- [ ] 推荐人 `1-ii` 、被推荐人 `1`  => （+ 0 天 / + 10 天）
- [ ] 推荐人 `1-ii` 、被推荐人 `2`  => （+ 0 天 / + 0 天）
- [ ] 推荐人 `2` 、被推荐人 `1`  => （+ 0 天 / + 10 天）
- [ ] 推荐人 `2` 、被推荐人 `2`  => （+ 0 天 / + 0 天）

**Comment by pengxiaoyan** [comment]
#  测试 - Stephen

## 测试 Case

### 推荐人 - 分享推荐给好友

1. 活动有效期内分享
   1. 推荐人数未满 10 人
   1. 推荐人数满 10 人
1. 活动有效期外分享
 
### 被推荐人 - 点击分享链接后

1. 首次注册登陆
1. 非首次注册登陆

## 测试结果

### 非订阅

- [ ] 推荐人 `1-i` 、被推荐人 `1`  => （+ 20 天 / + 10 天）
- [ ] 推荐人 `1-i` 、被推荐人 `2`  => （+ 0 天 / + 0 天）
- [ ] 推荐人 `1-ii` 、被推荐人 `1`  => （+ 0 天 / + 10 天）
- [ ] 推荐人 `1-ii` 、被推荐人 `2`  => （+ 0 天 / + 0 天）
- [ ] 推荐人 `2` 、被推荐人 `1`  => （+ 0 天 / + 10 天）
- [ ] 推荐人 `2` 、被推荐人 `2`  => （+ 0 天 / + 0 天）

### 订阅

- [ ] 推荐人 `1-i` 、被推荐人 `1`  => （+ 20 天 / + 10 天）
- [ ] 推荐人 `1-i` 、被推荐人 `2`  => （+ 0 天 / + 0 天）
- [ ] 推荐人 `1-ii` 、被推荐人 `1`  => （+ 0 天 / + 10 天）
- [ ] 推荐人 `1-ii` 、被推荐人 `2`  => （+ 0 天 / + 0 天）
- [ ] 推荐人 `2` 、被推荐人 `1`  => （+ 0 天 / + 10 天）
- [ ] 推荐人 `2` 、被推荐人 `2`  => （+ 0 天 / + 0 天）

**Comment by Johnsonkk2020** [comment]
#  测试 - Johnson

## 测试 Case

### 推荐人 - 分享推荐给好友

1. 活动有效期内分享
   1. 推荐人数未满 10 人
   1. 推荐人数满 10 人
1. 活动有效期外分享
 
### 被推荐人 - 点击分享链接后

1. 首次注册登陆
1. 非首次注册登陆

## 测试结果

### 非订阅

- [ ] 推荐人 `1-i` 、被推荐人 `1`  => （+ 20 天 / + 10 天）
- [ ] 推荐人 `1-i` 、被推荐人 `2`  => （+ 0 天 / + 0 天）
- [ ] 推荐人 `1-ii` 、被推荐人 `1`  => （+ 0 天 / + 10 天）
- [ ] 推荐人 `1-ii` 、被推荐人 `2`  => （+ 0 天 / + 0 天）
- [ ] 推荐人 `2` 、被推荐人 `1`  => （+ 0 天 / + 10 天）
- [ ] 推荐人 `2` 、被推荐人 `2`  => （+ 0 天 / + 0 天）

### 订阅

- [ ] 推荐人 `1-i` 、被推荐人 `1`  => （+ 20 天 / + 10 天）
- [ ] 推荐人 `1-i` 、被推荐人 `2`  => （+ 0 天 / + 0 天）
- [ ] 推荐人 `1-ii` 、被推荐人 `1`  => （+ 0 天 / + 10 天）
- [ ] 推荐人 `1-ii` 、被推荐人 `2`  => （+ 0 天 / + 0 天）
- [ ] 推荐人 `2` 、被推荐人 `1`  => （+ 0 天 / + 10 天）
- [ ] 推荐人 `2` 、被推荐人 `2`  => （+ 0 天 / + 0 天）

**Comment by Johnsonkk2020** [comment]
https://ohjcz.test-app.link/LsoVVzool6

**Comment by pengxiaoyan** [comment]
https://ohjcz.test-app.link/eTqI8Kqrl6

**Comment by pengxiaoyan** [comment]
https://ohjcz.test-app.link/mXE4xOttl6
